### ISSUE TITLE
Improve git repo age rule

### ISSUE THREAD

**Issue by andys8** [sindresorhus/awesome-lint#105]
I integrated `awesome-lint` for a new project. I keep continuously adding content. Because `awesome-lint` is running on CI and the repository is newly created, the job fails every time. I'd be interested in dead links or relevant warnings but there is no action one could take to solve this. Therefore it's an odd rule.

> Git repository must be at least 30 days old  remark-lint:awesome-git-repo-age

What's the best way to approach it? Can the rule be disabled? Can it be configured to be a warning or be defined as warning in the project?

Thanks for your help :)

**Comment by chrvadala** [comment]
I'm having the same issue and I suspect that it is a firewall issue. 
On my PC lint rule pass, but it fails on github actions https://github.com/chrvadala/awesome-protocols/actions

**Comment by 2color** [comment]
This is because the rule checks the time different against the root hash of the repository. By default, Github Actions will only clone the repo with `--depth 1` which means it has only the latest commit. 

On Github actions, you can define the `fetch-depth: 0` to fetch all commits and for the [linter rule](https://github.com/sindresorhus/awesome-lint/blob/master/rules/git-repo-age.js#L15-L17) to work:

The following Github action should work:

```yaml
name: test
on: push

jobs:
  awesome-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm test
````
