### ISSUE TITLE
git-repo-age rule fails on Travis

### ISSUE THREAD

**Issue by carlosperate** [sindresorhus/awesome-lint#45]
Can be seen here: https://travis-ci.org/carlosperate/awesome-microbit/builds/427309076

A repository hosted on GitHub (https://github.com/carlosperate/awesome-microbit/) and the travis script doesn't have anything complex going on: 
https://github.com/carlosperate/awesome-microbit/blob/f2d3fae2faf85f4e4022ffa8057870a7c48912f9/.travis.yml
```yml
language: node_js
node_js:
  - 'node'

before_install:
  - rvm install 2.2.2

install:
  - npm install --global awesome-lint
  - gem install awesome_bot

script:
  - awesome-lint README.md
  - awesome_bot README.md --allow-redirect --allow-dupe
```

Travis log outputs:

```
$ awesome-lint README.md
- Linting
✖ Linting
README.md:333:3
✖1:1  Awesome list must reside in a valid git repositoryawesome/git-repo-age
```
